# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('derby_darts', '0024_auto_20151130_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=256)),
                ('is_county', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='derby_darts.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to='derby_darts.Team'),
        ),
    ]
