# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('derby_darts', '0025_auto_20160729_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPointDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=128, null=True)),
                ('num_of_points', models.SmallIntegerField(default=0)),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derby_darts.SeasonStanding')),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-is_county', 'name']},
        ),
    ]
