# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derby_darts', '0027_auto_20170112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
